sonar.projectKey=GauravSahu2_high-assurance-api
sonar.organization=gauravsahu2
sonar.projectName=High-Assurance API
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
sonar.exclusions=**/node_modules/**,**/venv/**,**/mutants/**
sonar.coverage.exclusions=tests/**
