apiVersion: v1
kind: Service
metadata:
  name: hsa-api-service
  namespace: hsa-prod
spec:
  selector:
    app: hsa-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
