"""Add auth fields to accounts

Revision ID: a5645b04229d
Revises: d8d6ec8953ab
Create Date: 2026-04-03 18:21:00.179289

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a5645b04229d'
down_revision: str | None = 'd8d6ec8953ab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.alter_column('response_body',
               existing_type=sqlite.JSON(),
               nullable=False)

    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), nullable=False))

    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.alter_column('response_body',
               existing_type=sqlite.JSON(),
               nullable=True)

    # ### end Alembic commands ###
